services:
  django:
    build:
      context: ../
      dockerfile: crypto_service/Dockerfile
    container_name: crypto_service
    command: >
      sh -c "cd crypto_service &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../:/app
    ports:
      - "8002:8000"
