# Generated by Django 5.1.5 on 2025-02-06 13:42

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_service", "0002_alter_customuser_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, default="UA", max_length=2
            ),
        ),
    ]
